# Generated by Django 3.0.5 on 2020-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
